stages:
  - test

variables:
  USERNAME: gitlab

test:
  stage: test
  image: python:3.11.8-slim
  before_script:
    - apt-get update && apt-get install -y git
    - python -m pip install -r requirements-ci.txt .
  script:
    - pytest --junitxml=report.xml tests/
  artifacts:
    reports:
      junit: report.xml

