project:
  type: website

website:
  title: "evalmy.ai"
  repo-url: https://github.com/evalmy-ai/evalmyai-python
  repo-branch: main
  repo-subdir: docs
  back-to-top-navigation: true
  page-navigation: true

  sidebar:
    style: docked
    search: true
    contents:
      - context.qmd
      - scoring.qmd
      - batch.qmd


format:
  profinit-html:
    toc: true
    title-block-banner: false
    warning: false

execute:
  freeze: auto
