project:
  type: website

website:
  title: "evalmy.ai"
  repo-url: https://github.com/evalmy-ai/evalmyai-python
  repo-branch: main
  repo-subdir: docs
  back-to-top-navigation: true
  page-navigation: true

  navbar:
    search: true
    tools:
      - icon: git
        url: https://github.com/evalmy-ai/evalmyai-python
    left:
      - sidebar:start
      -
        text: API
        href: api/index.qmd

  sidebar:
    - id: start
      title: Get started
      style: docked
      contents: 
        - first_steps.qmd
        - context.qmd
        - scoring.qmd
        - batch.qmd

metadata-files:
  - api/_sidebar.yml
  
quartodoc:
  package: evalmyai
  dir: api
  title: API
  parser: google

  sections:
    - title: Classes
      contents:
        - Evaluator
    - title: Evaluator
      contents:
        - Evaluator.set_scoring
        - Evaluator.evaluate
        - Evaluator.evaluate_batch
        - Evaluator.evaluate_test_case
        - Evaluator.evaluate_dataset

format:
  profinit-html:
    toc: true
    title-block-banner: false
    warning: false

execute:
  freeze: auto
